server:
  port: 8080
spring:
  application:
    name: MyBlog
  datasource:
    url: jdbc:postgresql://localhost:5432/my-blog
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: mySecretKey
  expiration: 3600000
  refresh-token.expiration: 86400000

